### ISSUE TITLE
 KeyError: raise KeyError("{} not in index".format(not_found))

### ISSUE THREAD

**Issue by archaemenes** [huangger/pyNBS#7]
Traceback (most recent call last):
  File "./run_pyNBS.py", line 214, in <module>
    Hlist.append(pyNBS_single.NBS_single(sm_mat, knnGlap, propNet=network, propNet_kernel=kernel, k=params['netNMF_k'], **params))
  File "build/bdist.linux-x86_64/egg/pyNBS/pyNBS_single.py", line 41, in NBS_single
  File "build/bdist.linux-x86_64/egg/pyNBS/pyNBS_core.py", line 83, in subsample_sm_mat
  File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 126, in __getitem__
    return self._getitem_axis(key, axis=axis)
  File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 1088, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 1205, in _getitem_iterable
    raise_missing=False)
  File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "[u'HSPA6', u'C4B', u'SMG6', u'IFNA13', u'WEE2', u'SV2C', u'IFNA17', u'IRAK4', u'IFNA14', u'DHX9', u'GSC2', u'WRN', u'CAMK2G', u'CEP89', u'DEPDC1B', u'ORM1', u'MAX', u'PIDD1', u'ANGPTL4', u'IL11', u'YBX1', u'ITGA8', u'IL21R', u'CDKN1C', u'ITGA2', u'ITGA3', u'BUB1', u'BAZ2B', u'APOA1', u'CHIC2', u'IFNL1', u'IFNL2', u'IFNL3', u'KIR2DS4', u'KIR2DS5', u'KIR2DS3', u'KIR2DS1', u'CCL28', u'C4A', u'H3F3A', u'JAK1', u'CCL20', u'CCL23', u'CCL24', u'CCL27', u'HMMR', u'VEGFD', u'COL4A2', u'VEGFC', u'ANAPC2', u'IRGM', u'ZEB2', u'INS', u'KIR2DL3', u'FRAT1', u'FRAT2', u'ITGAL', u'SIGIRR', u'GADD45A', u'IL11RA', u'HLF', u'HES2', u'FOXC2', u'CD19', u'SESN3', u'SMAD5', u'SMAD2', u'LTB4R', u'POLB', u'TAF15', u'PIK3AP1', u'CDC7', u'PKLR', u'ASPM', u'TFPT', u'RBM10', u'PTTG2', u'DDB1', u'ADGRB1', u'PLA2G3', u'IL17D', u'LAMA4', u'IL17A', u'IL17C', u'TCEA1', u'PRKAR1B', u'KIR2DL5A', u'F2', u'ZNF638', u'LMO1', u'AFDN', u'ATP1A1', u'CDC42', u'ERC1', u'CHP1', u'CTNNB1', u'NGFR', u'CAD', u'NFX1', u'HERPUD1', u'MYOD1', u'SELENOS', u'CXCR2', u'PGR', u'APOL3', u'APOL2', u'EPS15', u'RTN4', u'NCR3', u'FGFR1OP', u'HGF', u'PLA2G4B', u'TCL1A', u'EIF4E2', u'PRCC', u'C3AR1', u'MAP3K11', u'EWSR1', u'IKBKB', u'CXCL13', u'IFNLR1', u'RARB', u'KLF6', u'ARHGEF6', u'NFE2L2', u'WNT10B', u'IL36A', u'HNRNPA2B1', u'LIPA', u'IFITM1', u'EXT1', u'DAAM2', u'RGS3', u'DFFA', u'DFFB', u'LEFTY1', u'SNAI2', u'SNAI1', u'PAFAH1B2', u'ZC3H11A', u'FABP7', u'ARID1B', u'CSF2', u'CSF3', u'CYLD', u'ELK4', u'APC', u'STRADA', u'PAK2', u'FABP3', u'WNT2B', u'CCL4', u'SPTAN1', u'WIF1', u'ARFGAP3', u'ARFGAP1', u'VANGL2', u'STAM', u'DHX35', u'CYSLTR1', u'MYCL', u'U2AF1', u'PKM', u'FARP2', u'TCF3', u'MRE11', u'MLLT11', u'CCDC6', u'EIF4E', u'FZD4', u'EGLN3', u'MGA', u'PLA2G10', u'PPP5C', u'NEIL1', u'BTC', u'NSD1', u'TP53BP1', u'CD74', u'EPHX2', u'CHAD', u'ZNF331', u'HDAC9', u'RFC4', u'ATM', u'ZFHX3', u'SPRY3', u'SPRY2', u'FABP4', u'ELOB', u'ELOC', u'MALAT1', u'CACNB4', u'MLF1', u'NLRP3', u'MECOM', u'MYH9', u'RPS6KB1', u'FANCE', u'MAPK1', u'LSM14A', u'TNFSF4', u'COL5A2', u'ENO1', u'FOXL2', u'NUTM1', u'UNG', u'TAOK2', u'TAOK3', u'ACOX2', u'CCL4L1', u'CCL4L2', u'KNG1', u'ALDH2', u'RAD51', u'MAD2L2', u'KTN1', u'ERCC1', u'PRDX2', u'PRKAA1', u'SPECC1', u'ALOX15', u'APOA5', u'PRKX', u'AXIN2', u'AXIN1', u'TNFRSF12A', u'UCN', u'KLRC1', u'XPO1', u'NR4A3', u'PRKCB', u'ENDOG', u'PSME3', u'UCP1', u'COL6A2', u'ACKR3', u'VTI1A', u'CANT1', u'PTCH2', u'KAT6B', u'KAT6A', u'CACNG7', u'SSX4', u'IL25', u'AFF1', u'IL26', u'SOX17', u'CAV1', u'CACNA1H', u'CACNA1I', u'IL12RB1', u'MAP3K3', u'GADD45B', u'CYP4F11', u'MAP3K6', u'PLA2G6', u'INHBA', u'MAGI2', u'GP5', u'MAP3K20', u'AQP7', u'FAM131B', u'BRCA2', u'NF1', u'IDH2', u'FPR2', u'TRIM27', u'CREB1', u'PER1', u'IFNA8', u'BRD4', u'MDM2', u'EHHADH', u'FGFR3', u'RSPO3', u'TCL6', u'CXCL3', u'CXCL8', u'KIF5B', u'PPFIBP1', u'KIT', u'RUNX1', u'ID2', u'CARM1', u'TNFRSF17', u'ITGA10', u'PTPN11', u'XRCC1', u'ARHGAP5', u'RICTOR', u'ACADL', u'LY86', u'SMURF1', u'STIL', u'CDC16', u'SRSF3', u'SRSF2', u'AHNAK', u'JUN', u'PDPN', u'EGF', u'PGK2', u'PLCB3', u'POM121', u'TRRAP', u'SFPQ', u'LAMC1', u'PTPN7', u'PTPN6', u'ASPSCR1', u'PROK2', u'JMJD7-PLA2G4B', u'POLE3', u'PPP2R5D', u'FGF22', u'LAMTOR3', u'MKNK2', u'CD4', u'CCR2', u'CCR3', u'ANAPC13', u'CCR7', u'IL1B', u'STAT4', u'HOXA13', u'HBEGF', u'FOSL1', u'SRC', u'HMGCS2', u'ACACA', u'TAL2', u'ACSS1', u'PLA2G2C', u'PLA2G2D', u'CD8A', u'CD180', u'RAD51B', u'IL18', u'SFRP1', u'SFRP5', u'IL10', u'WNT2', u'TDG', u'WNT6', u'IL6', u'IL4', u'IL5', u'COL1A2', u'IL3', u'COL1A1', u'IL9', u'MAP4K1', u'AOX1', u'PPP2R1B', u'MAP4K4', u'ADGRE5', u'CYCS', u'FCGR3B', u'BMPR1A', u'MAP2K1', u'MAP2K6', u'FMR1', u'PRICKLE2', u'WASF2', u'KIR2DL2', u'STAM2', u'TERC', u'RPL22', u'GAL', u'P2RX7', u'NUTM2A', u'NRG1', u'CYP4A22', u'KMT2C', u'KMT2A', u'KMT2D', u'SPOP', u'MCM7', u'MCM4', u'POU5F1', u'TSHR', u'ALDOC', u'DUSP10', u'CASP1', u'MAPT', u'LNPEP', u'NAB2', u'TNFSF8', u'PTGS1', u'SSX2', u'AKT3', u'MAFB', u'S100A12', u'ZYX', u'EIF1AX', u'ANAPC10', u'INPP4A', u'NTRK3', u'XCL2', u'XCL1', u'SLC34A2', u'CACNA2D4', u'MYC', u'MYB', u'CD28', u'CD22', u'CCR10', u'CD24', u'PRF1', u'UBR5', u'CAB39L', u'SOCS1', u'ACSL5', u'ULBP2', u'XRN1', u'TLR4', u'ULBP1', u'CCL3L3', u'CCL3L1', u'STMN1', u'PDGFA', u'PABPC1', u'NOX1', u'CD8B', u'MLLT6', u'TGFA', u'JMY', u'AMER1', u'TRAF7', u'THBS2', u'PIK3R6', u'PPP1R12A', u'PIK3R1', u'IL22RA1', u'SMC1B', u'TRA', u'FCGR2B', u'TRB', u'MYL10', u'ORC3', u'PAK5', u'FGF7', u'FGF6', u'KDSR', u'ETV5', u'CDC26', u'MPL', u'SDC3', u'G6PC', u'TNFAIP3', u'PPP2R1A', u'BAIAP2', u'AIFM1', u'IL17RB', u'IL17RA', u'RAD23A', u'POT1', u'TLR10', u'CCNG2', u'MAPK13', u'TNPO2', u'TICAM2', u'NANOG', u'FZD6', u'FZD8', u'CACNB1', u'TEC', u'GP1BA', u'GP1BB', u'NECTIN2', u'NECTIN3', u'NECTIN1', u'POLD4', u'NBN', u'NECTIN4', u'DUSP4', u'DUSP7', u'FGF10', u'DUSP2', u'FEV', u'SERPINF2', u'MNAT1', u'MLST8', u'TNFRSF13B', u'MAPK8IP1', u'PARVA', u'SOS2', u'CCL16', u'ADH4', u'CCL18', u'CCL19', u'ID4', u'IFNA7', u'IFNA6', u'LEP', u'CLP1', u'NKX3-1', u'SMARCE1', u'NUMA1', u'BCL11A', u'IL12B', u'IL12A', u'CNTNAP1', u'PF4', u'ELF3', u'NOTCH3', u'MAPKAPK5', u'RMI2', u'NEDD4L', u'WNT8A', u'WNT8B', u'LDHA', u'LRP10', u'TRAF1', u'ULK1', u'PDGFD', u'ADH1A', u'RAD21', u'ORC6', u'GTF2H2', u'ORC4', u'ORC5', u'ORC2', u'IGL', u'GTF2H5', u'ORC1', u'CLTCL1', u'LEPR', u'CNTRL', u'RASA2', u'ACTN2', u'DIS3', u'PTPRR', u'ACTN4', u'TINF2', u'EZR', u'PTPRF', u'GRIN2A', u'BRAF', u'PTPRM', u'ATF1'] not in index"

**Comment by hett888** [comment]
I encountered the same problem. Have you solved it?

**Comment by hett888** [comment]
> Traceback (most recent call last): File "./run_pyNBS.py", line 214, in Hlist.append(pyNBS_single.NBS_single(sm_mat, knnGlap, propNet=network, propNet_kernel=kernel, k=params['netNMF_k'], **params)) File "build/bdist.linux-x86_64/egg/pyNBS/pyNBS_single.py", line 41, in NBS_single File "build/bdist.linux-x86_64/egg/pyNBS/pyNBS_core.py", line 83, in subsample_sm_mat File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 126, in **getitem** return self._getitem_axis(key, axis=axis) File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 1088, in _getitem_axis return self._getitem_iterable(key, axis=axis) File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 1205, in _getitem_iterable raise_missing=False) File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer raise_missing=raise_missing) File "/home/archaemenes/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer raise KeyError("{} not in index".format(not_found)) KeyError: "[u'HSPA6', u'C4B', u'SMG6', u'IFNA13', u'WEE2', u'SV2C', u'IFNA17', u'IRAK4', u'IFNA14', u'DHX9', u'GSC2', u'WRN', u'CAMK2G', u'CEP89', u'DEPDC1B', u'ORM1', u'MAX', u'PIDD1', u'ANGPTL4', u'IL11', u'YBX1', u'ITGA8', u'IL21R', u'CDKN1C', u'ITGA2', u'ITGA3', u'BUB1', u'BAZ2B', u'APOA1', u'CHIC2', u'IFNL1', u'IFNL2', u'IFNL3', u'KIR2DS4', u'KIR2DS5', u'KIR2DS3', u'KIR2DS1', u'CCL28', u'C4A', u'H3F3A', u'JAK1', u'CCL20', u'CCL23', u'CCL24', u'CCL27', u'HMMR', u'VEGFD', u'COL4A2', u'VEGFC', u'ANAPC2', u'IRGM', u'ZEB2', u'INS', u'KIR2DL3', u'FRAT1', u'FRAT2', u'ITGAL', u'SIGIRR', u'GADD45A', u'IL11RA', u'HLF', u'HES2', u'FOXC2', u'CD19', u'SESN3', u'SMAD5', u'SMAD2', u'LTB4R', u'POLB', u'TAF15', u'PIK3AP1', u'CDC7', u'PKLR', u'ASPM', u'TFPT', u'RBM10', u'PTTG2', u'DDB1', u'ADGRB1', u'PLA2G3', u'IL17D', u'LAMA4', u'IL17A', u'IL17C', u'TCEA1', u'PRKAR1B', u'KIR2DL5A', u'F2', u'ZNF638', u'LMO1', u'AFDN', u'ATP1A1', u'CDC42', u'ERC1', u'CHP1', u'CTNNB1', u'NGFR', u'CAD', u'NFX1', u'HERPUD1', u'MYOD1', u'SELENOS', u'CXCR2', u'PGR', u'APOL3', u'APOL2', u'EPS15', u'RTN4', u'NCR3', u'FGFR1OP', u'HGF', u'PLA2G4B', u'TCL1A', u'EIF4E2', u'PRCC', u'C3AR1', u'MAP3K11', u'EWSR1', u'IKBKB', u'CXCL13', u'IFNLR1', u'RARB', u'KLF6', u'ARHGEF6', u'NFE2L2', u'WNT10B', u'IL36A', u'HNRNPA2B1', u'LIPA', u'IFITM1', u'EXT1', u'DAAM2', u'RGS3', u'DFFA', u'DFFB', u'LEFTY1', u'SNAI2', u'SNAI1', u'PAFAH1B2', u'ZC3H11A', u'FABP7', u'ARID1B', u'CSF2', u'CSF3', u'CYLD', u'ELK4', u'APC', u'STRADA', u'PAK2', u'FABP3', u'WNT2B', u'CCL4', u'SPTAN1', u'WIF1', u'ARFGAP3', u'ARFGAP1', u'VANGL2', u'STAM', u'DHX35', u'CYSLTR1', u'MYCL', u'U2AF1', u'PKM', u'FARP2', u'TCF3', u'MRE11', u'MLLT11', u'CCDC6', u'EIF4E', u'FZD4', u'EGLN3', u'MGA', u'PLA2G10', u'PPP5C', u'NEIL1', u'BTC', u'NSD1', u'TP53BP1', u'CD74', u'EPHX2', u'CHAD', u'ZNF331', u'HDAC9', u'RFC4', u'ATM', u'ZFHX3', u'SPRY3', u'SPRY2', u'FABP4', u'ELOB', u'ELOC', u'MALAT1', u'CACNB4', u'MLF1', u'NLRP3', u'MECOM', u'MYH9', u'RPS6KB1', u'FANCE', u'MAPK1', u'LSM14A', u'TNFSF4', u'COL5A2', u'ENO1', u'FOXL2', u'NUTM1', u'UNG', u'TAOK2', u'TAOK3', u'ACOX2', u'CCL4L1', u'CCL4L2', u'KNG1', u'ALDH2', u'RAD51', u'MAD2L2', u'KTN1', u'ERCC1', u'PRDX2', u'PRKAA1', u'SPECC1', u'ALOX15', u'APOA5', u'PRKX', u'AXIN2', u'AXIN1', u'TNFRSF12A', u'UCN', u'KLRC1', u'XPO1', u'NR4A3', u'PRKCB', u'ENDOG', u'PSME3', u'UCP1', u'COL6A2', u'ACKR3', u'VTI1A', u'CANT1', u'PTCH2', u'KAT6B', u'KAT6A', u'CACNG7', u'SSX4', u'IL25', u'AFF1', u'IL26', u'SOX17', u'CAV1', u'CACNA1H', u'CACNA1I', u'IL12RB1', u'MAP3K3', u'GADD45B', u'CYP4F11', u'MAP3K6', u'PLA2G6', u'INHBA', u'MAGI2', u'GP5', u'MAP3K20', u'AQP7', u'FAM131B', u'BRCA2', u'NF1', u'IDH2', u'FPR2', u'TRIM27', u'CREB1', u'PER1', u'IFNA8', u'BRD4', u'MDM2', u'EHHADH', u'FGFR3', u'RSPO3', u'TCL6', u'CXCL3', u'CXCL8', u'KIF5B', u'PPFIBP1', u'KIT', u'RUNX1', u'ID2', u'CARM1', u'TNFRSF17', u'ITGA10', u'PTPN11', u'XRCC1', u'ARHGAP5', u'RICTOR', u'ACADL', u'LY86', u'SMURF1', u'STIL', u'CDC16', u'SRSF3', u'SRSF2', u'AHNAK', u'JUN', u'PDPN', u'EGF', u'PGK2', u'PLCB3', u'POM121', u'TRRAP', u'SFPQ', u'LAMC1', u'PTPN7', u'PTPN6', u'ASPSCR1', u'PROK2', u'JMJD7-PLA2G4B', u'POLE3', u'PPP2R5D', u'FGF22', u'LAMTOR3', u'MKNK2', u'CD4', u'CCR2', u'CCR3', u'ANAPC13', u'CCR7', u'IL1B', u'STAT4', u'HOXA13', u'HBEGF', u'FOSL1', u'SRC', u'HMGCS2', u'ACACA', u'TAL2', u'ACSS1', u'PLA2G2C', u'PLA2G2D', u'CD8A', u'CD180', u'RAD51B', u'IL18', u'SFRP1', u'SFRP5', u'IL10', u'WNT2', u'TDG', u'WNT6', u'IL6', u'IL4', u'IL5', u'COL1A2', u'IL3', u'COL1A1', u'IL9', u'MAP4K1', u'AOX1', u'PPP2R1B', u'MAP4K4', u'ADGRE5', u'CYCS', u'FCGR3B', u'BMPR1A', u'MAP2K1', u'MAP2K6', u'FMR1', u'PRICKLE2', u'WASF2', u'KIR2DL2', u'STAM2', u'TERC', u'RPL22', u'GAL', u'P2RX7', u'NUTM2A', u'NRG1', u'CYP4A22', u'KMT2C', u'KMT2A', u'KMT2D', u'SPOP', u'MCM7', u'MCM4', u'POU5F1', u'TSHR', u'ALDOC', u'DUSP10', u'CASP1', u'MAPT', u'LNPEP', u'NAB2', u'TNFSF8', u'PTGS1', u'SSX2', u'AKT3', u'MAFB', u'S100A12', u'ZYX', u'EIF1AX', u'ANAPC10', u'INPP4A', u'NTRK3', u'XCL2', u'XCL1', u'SLC34A2', u'CACNA2D4', u'MYC', u'MYB', u'CD28', u'CD22', u'CCR10', u'CD24', u'PRF1', u'UBR5', u'CAB39L', u'SOCS1', u'ACSL5', u'ULBP2', u'XRN1', u'TLR4', u'ULBP1', u'CCL3L3', u'CCL3L1', u'STMN1', u'PDGFA', u'PABPC1', u'NOX1', u'CD8B', u'MLLT6', u'TGFA', u'JMY', u'AMER1', u'TRAF7', u'THBS2', u'PIK3R6', u'PPP1R12A', u'PIK3R1', u'IL22RA1', u'SMC1B', u'TRA', u'FCGR2B', u'TRB', u'MYL10', u'ORC3', u'PAK5', u'FGF7', u'FGF6', u'KDSR', u'ETV5', u'CDC26', u'MPL', u'SDC3', u'G6PC', u'TNFAIP3', u'PPP2R1A', u'BAIAP2', u'AIFM1', u'IL17RB', u'IL17RA', u'RAD23A', u'POT1', u'TLR10', u'CCNG2', u'MAPK13', u'TNPO2', u'TICAM2', u'NANOG', u'FZD6', u'FZD8', u'CACNB1', u'TEC', u'GP1BA', u'GP1BB', u'NECTIN2', u'NECTIN3', u'NECTIN1', u'POLD4', u'NBN', u'NECTIN4', u'DUSP4', u'DUSP7', u'FGF10', u'DUSP2', u'FEV', u'SERPINF2', u'MNAT1', u'MLST8', u'TNFRSF13B', u'MAPK8IP1', u'PARVA', u'SOS2', u'CCL16', u'ADH4', u'CCL18', u'CCL19', u'ID4', u'IFNA7', u'IFNA6', u'LEP', u'CLP1', u'NKX3-1', u'SMARCE1', u'NUMA1', u'BCL11A', u'IL12B', u'IL12A', u'CNTNAP1', u'PF4', u'ELF3', u'NOTCH3', u'MAPKAPK5', u'RMI2', u'NEDD4L', u'WNT8A', u'WNT8B', u'LDHA', u'LRP10', u'TRAF1', u'ULK1', u'PDGFD', u'ADH1A', u'RAD21', u'ORC6', u'GTF2H2', u'ORC4', u'ORC5', u'ORC2', u'IGL', u'GTF2H5', u'ORC1', u'CLTCL1', u'LEPR', u'CNTRL', u'RASA2', u'ACTN2', u'DIS3', u'PTPRR', u'ACTN4', u'TINF2', u'EZR', u'PTPRF', u'GRIN2A', u'BRAF', u'PTPRM', u'ATF1'] not in index"

I encountered the same problem. Have you solved it?
